#!/bin/bash
# Copy extracted libraries to system paths for Xvfb GLX + Godot support
SRC=/root/localroot/usr/lib/x86_64-linux-gnu
DST=/usr/lib/x86_64-linux-gnu

# GL/EGL/GLES libraries
cp "$SRC/libGL.so.1" "$DST/"
cp "$SRC/libGL.so.1.7.0" "$DST/"
cp "$SRC/libGLX.so.0" "$DST/"
cp "$SRC/libGLX.so.0.0.0" "$DST/"
cp "$SRC/libGLX_mesa.so.0" "$DST/"
cp "$SRC/libGLX_mesa.so.0.0.0" "$DST/"
cp "$SRC/libGLX_indirect.so.0" "$DST/"
cp "$SRC/libGLdispatch.so.0" "$DST/"
cp "$SRC/libGLdispatch.so.0.0.0" "$DST/"
cp "$SRC/libEGL.so.1" "$DST/"
cp "$SRC/libEGL.so.1.1.0" "$DST/"
cp "$SRC/libEGL_mesa.so.0" "$DST/"
cp "$SRC/libEGL_mesa.so.0.0.0" "$DST/"
cp "$SRC/libGLESv2.so.2" "$DST/"
cp "$SRC/libGLESv2.so.2.1.0" "$DST/"
cp "$SRC/libgbm.so.1" "$DST/"
cp "$SRC/libgbm.so.1.0.0" "$DST/"
cp "$SRC/libglapi.so.0" "$DST/"
cp "$SRC/libglapi.so.0.0.0" "$DST/"

# X11 libraries
cp "$SRC/libX11.so.6" "$DST/"
cp "$SRC/libX11.so.6.4.0" "$DST/"
cp "$SRC/libxcb.so.1" "$DST/"
cp "$SRC/libxcb.so.1.1.0" "$DST/"
cp "$SRC/libxcb-dri2.so.0" "$DST/"
cp "$SRC/libxcb-dri2.so.0.0.0" "$DST/"
cp "$SRC/libxcb-dri3.so.0" "$DST/"
cp "$SRC/libxcb-dri3.so.0.1.0" "$DST/"
cp "$SRC/libxcb-glx.so.0" "$DST/"
cp "$SRC/libxcb-glx.so.0.0.0" "$DST/"
cp "$SRC/libxcb-present.so.0" "$DST/"
cp "$SRC/libxcb-present.so.0.0.0" "$DST/"
cp "$SRC/libxcb-randr.so.0" "$DST/"
cp "$SRC/libxcb-randr.so.0.1.0" "$DST/"
cp "$SRC/libxcb-shm.so.0" "$DST/"
cp "$SRC/libxcb-shm.so.0.0.0" "$DST/"
cp "$SRC/libxcb-sync.so.1" "$DST/"
cp "$SRC/libxcb-sync.so.1.0.0" "$DST/"
cp "$SRC/libxcb-xfixes.so.0" "$DST/"
cp "$SRC/libxcb-xfixes.so.0.0.0" "$DST/"
cp "$SRC/libxcb-xkb.so.1" "$DST/"
cp "$SRC/libxcb-xkb.so.1.0.0" "$DST/"
cp "$SRC/libXext.so.6" "$DST/"
cp "$SRC/libXext.so.6.4.0" "$DST/"
cp "$SRC/libXfixes.so.3" "$DST/"
cp "$SRC/libXfixes.so.3.1.0" "$DST/"
cp "$SRC/libXrender.so.1" "$DST/"
cp "$SRC/libXrender.so.1.3.0" "$DST/"
cp "$SRC/libXau.so.6" "$DST/"
cp "$SRC/libXau.so.6.0.0" "$DST/"
cp "$SRC/libXdmcp.so.6" "$DST/"
cp "$SRC/libXdmcp.so.6.0.0" "$DST/"
cp "$SRC/libXxf86vm.so.1" "$DST/"
cp "$SRC/libXxf86vm.so.1.0.0" "$DST/"

# DRM
cp "$SRC/libdrm.so.2" "$DST/"
cp "$SRC/libdrm.so.2.4.0" "$DST/"
cp "$SRC/libdrm_amdgpu.so.1" "$DST/"
cp "$SRC/libdrm_amdgpu.so.1.0.0" "$DST/"
cp "$SRC/libdrm_nouveau.so.2" "$DST/"
cp "$SRC/libdrm_nouveau.so.2.0.0" "$DST/"
cp "$SRC/libdrm_radeon.so.1" "$DST/"
cp "$SRC/libdrm_radeon.so.1.0.1" "$DST/"

# Wayland
cp "$SRC/libwayland-server.so.0" "$DST/"
cp "$SRC/libwayland-server.so.0.22.0" "$DST/"
cp "$SRC/libwayland-client.so.0" "$DST/"
cp "$SRC/libwayland-client.so.0.22.0" "$DST/"

# ALSA
cp "$SRC/libasound.so.2" "$DST/"
cp "$SRC/libasound.so.2.0.0" "$DST/"

# LLVM, sensors, misc
cp "$SRC/libLLVM-18.so" "$DST/"
cp "$SRC/libLLVM.so.18.1" "$DST/"
cp "$SRC/libsensors.so.5" "$DST/"
cp "$SRC/libsensors.so.5.0.0" "$DST/"
cp "$SRC/libunwind.so.8" "$DST/"
cp "$SRC/libunwind.so.8.0.1" "$DST/"
cp "$SRC/libunwind-x86_64.so.8" "$DST/"
cp "$SRC/libunwind-x86_64.so.8.0.1" "$DST/"
cp "$SRC/libepoxy.so.0" "$DST/"
cp "$SRC/libepoxy.so.0.0.0" "$DST/"
cp "$SRC/libpixman-1.so.0" "$DST/"
cp "$SRC/libpixman-1.so.0.42.2" "$DST/"
cp "$SRC/libnettle.so.8" "$DST/"
cp "$SRC/libnettle.so.8.8" "$DST/"
cp "$SRC/libelf-0.190.so" "$DST/"
cp "$SRC/libelf.so.1" "$DST/"
cp "$SRC/libxshmfence.so.1" "$DST/"
cp "$SRC/libxshmfence.so.1.0.0" "$DST/"

# DRI drivers
mkdir -p "$DST/dri"
cp "$SRC/dri/swrast_dri.so" "$DST/dri/"
cp "$SRC/dri/kms_swrast_dri.so" "$DST/dri/"

echo "Done: copied libraries to system paths"
