class_name FontSystem extends System

## FontSystem
##
## Font management system that handles:
## - Reading font configuration (public/pck_infos/fonts.json, generated by pack_assets.gd)
## - Loading font PCK via ResourceSystem
## - Creating and configuring FontFile objects
## - Managing default theme font
## - Providing font access API
##
## The system auto-loads fonts on initialization.
##
## Usage:
## ```
## # Event-based (recommended)
## func _ready():
##     var event_sys = env.get_system("EventSystem")
##     event_sys.register(FontLoadedEvent, _on_font_loaded)
##
## func _on_font_loaded(event: FontLoadedEvent):
##     if event.font_key == "press_start_2p":
##         $PixelLabel.add_theme_font_override("font", event.font)
##
## # Synchronous check
## var font_sys = env.get_system("FontSystem")
## if font_sys.is_font_loaded("ding_talk_jin_bu_ti_regular"):
##     var font = font_sys.get_font("ding_talk_jin_bu_ti_regular")
## ```


# ========================================
# Enums
# ========================================

## Font loading status
enum FontStatus {
	PENDING,         ## Not yet loaded
	LOADING,         ## Loading in progress
	LOADED,          ## Successfully loaded
	FAILED           ## Loading failed
}

## PCK loading status
enum PckStatus {
	NOT_LOADED,      ## PCK not loaded
	LOADING,         ## PCK downloading/loading
	LOADED,          ## PCK successfully loaded
	FAILED           ## PCK loading failed
}


# ========================================
# FontInfo Class
# ========================================

## Font information container
class FontInfo extends RefCounted:
	var key: String = ""
	var path: String = ""
	var status: int = FontStatus.PENDING
	var font_file: FontFile = null
	var error_message: String = ""


# ========================================
# Private Variables
# ========================================

## Loaded fonts (key -> FontInfo)
var _fonts: Dictionary = {}

## PCK loading status
var _pck_status: int = PckStatus.NOT_LOADED

## Manifest data
var _manifest: Dictionary = {}

## ResourceSystem reference
var _resource_system: ResourceSystem = null

## EventSystem reference
var _event_system: EventSystem = null

## Default font key
var _default_font_key: String = ""

## Whether waiting for ResourceSystem Node (web only)
var _waiting_for_node: bool = false


# ========================================
# Lifecycle
# ========================================

func _on_init() -> void:
	_resource_system = get_system("ResourceSystem") as ResourceSystem
	_event_system = get_system("EventSystem") as EventSystem

	if _resource_system == null:
		log_error("[FontSystem] ResourceSystem not found")
		return

	if _event_system == null:
		log_error("[FontSystem] EventSystem not found")
		return

	# Load manifest (always possible, it's in main PCK)
	_load_manifest()

	# Start PCK download (may need to wait for Node on web)
	_start_pck_download()

	log_info("[FontSystem] Initialized")


func _on_shutdown() -> void:
	# Unregister event handler if still connected
	if _event_system and _waiting_for_node:
		_event_system.unregister(ResourceNodeReadyEvent, _on_resource_node_ready)

	_fonts.clear()
	_manifest.clear()
	_resource_system = null
	_event_system = null
	log_info("[FontSystem] Shutdown")


# ========================================
# Public API
# ========================================

## Get a loaded font by key
##
## @param font_key Font configuration key
## @returns FontFile or null if not loaded
func get_font(font_key: String) -> FontFile:
	if not _fonts.has(font_key):
		return null

	var info: FontInfo = _fonts[font_key]
	if info.status != FontStatus.LOADED:
		return null

	return info.font_file


## Get font loading status
##
## @param font_key Font configuration key
## @returns FontStatus enum value
func get_font_status(font_key: String) -> int:
	if not _fonts.has(font_key):
		return FontStatus.PENDING
	var info: FontInfo = _fonts[font_key]
	return info.status


## Check if a font is loaded
##
## @param font_key Font configuration key
## @returns true if font is fully loaded
func is_font_loaded(font_key: String) -> bool:
	if not _fonts.has(font_key):
		return false
	var info: FontInfo = _fonts[font_key]
	return info.status == FontStatus.LOADED


## Check if PCK is loaded
##
## @returns true if PCK is successfully loaded
func is_pck_loaded() -> bool:
	return _pck_status == PckStatus.LOADED


## Set and apply the default font
##
## @param font_key Font configuration key
func set_default_font(font_key: String) -> void:
	_default_font_key = font_key

	if is_font_loaded(font_key):
		var font: FontFile = get_font(font_key)
		if font:
			_apply_default_font(font)


## Get the default font
##
## @returns Default FontFile or null
func get_default_font() -> FontFile:
	return get_font(_default_font_key)


## Get all available font keys from manifest
##
## @returns Array of font key strings
func get_font_keys() -> Array[String]:
	var result: Array[String] = []
	for key: String in _fonts:
		result.append(key)
	return result


# ========================================
# Manifest Loading
# ========================================

func _load_manifest() -> void:
	var manifest_path: String = "res://public/pck_infos/fonts.json"

	# Read pck_info (generated by pack_assets.gd, packed in main PCK)
	var file: FileAccess = FileAccess.open(manifest_path, FileAccess.READ)
	if file == null:
		# During build (headless script), pck_info doesn't exist yet - this is normal
		# During runtime, it should exist (packed in main PCK)
		if OS.has_feature("editor") or DisplayServer.get_name() == "headless":
			log_info("[FontSystem] fonts.json not found (normal during build)")
		else:
			log_error("[FontSystem] Cannot open fonts.json")
		return

	var json: JSON = JSON.new()
	var error: Error = json.parse(file.get_as_text())
	file.close()

	if error != OK:
		log_error("[FontSystem] Invalid JSON: %s" % json.get_error_message())
		return

	if not json.data is Dictionary:
		log_error("[FontSystem] fonts.json root must be Dictionary")
		return
	
	_manifest = json.data

	# Save default font key
	_default_font_key = _manifest.get("default_font", "")

	# Initialize font configs
	var fonts: Array = _manifest.get("fonts", [])
	for font_data: Variant in fonts:
		if not font_data is Dictionary:
			continue

		var font_dict: Dictionary = font_data
		var info: FontInfo = FontInfo.new()
		info.key = font_dict.get("key", "")
		info.path = font_dict.get("path", "")
		info.status = FontStatus.PENDING

		if not info.key.is_empty():
			_fonts[info.key] = info

	log_info("[FontSystem] Loaded manifest with %d fonts" % _fonts.size())


## Start PCK download, waiting for Node if needed on web
func _start_pck_download() -> void:
	if _manifest.is_empty():
		# No manifest = no fonts to load (normal during build)
		return

	if OS.has_feature("web"):
		# Web platform: need Node for HTTP requests
		if _resource_system.get_node() != null:
			# Node already available, download immediately
			_download_pck()
		else:
			# Wait for ResourceNodeReadyEvent
			_waiting_for_node = true
			_event_system.register(ResourceNodeReadyEvent, _on_resource_node_ready)
			log_info("[FontSystem] Waiting for ResourceSystem Node...")
	else:
		# Desktop: load directly, no HTTP needed
		_download_pck()


## Handler for ResourceNodeReadyEvent
func _on_resource_node_ready(_event: ResourceNodeReadyEvent) -> void:
	if not _waiting_for_node:
		return

	_waiting_for_node = false
	_event_system.unregister(ResourceNodeReadyEvent, _on_resource_node_ready)

	log_info("[FontSystem] ResourceSystem Node ready, starting PCK download")
	_download_pck()


# ========================================
# PCK Loading
# ========================================

func _download_pck() -> void:
	var pck_file: String = _manifest.get("pck_file", "")
	if pck_file.is_empty():
		# Empty pck_file = placeholder manifest during build, skip silently
		return

	_pck_status = PckStatus.LOADING
	log_info("[FontSystem] Loading PCK: %s" % pck_file)

	if OS.has_feature("web"):
		# Web platform: download via ResourceSystem (relative path, same directory)
		var base_url: String = _get_web_base_url()
		if base_url.is_empty():
			_on_pck_load_failed("Failed to get web base URL")
			return

		var config: ResourceConfig = ResourceConfig.new()
		config.key = "fonts_pck"
		config.type = ResourceTypes.Type.PCK
		config.skip_cache_busting = true  # Filename already versioned

		# Construct full URL from current page location
		config.remote_url = base_url + pck_file

		log_info("[FontSystem] Remote URL: %s" % config.remote_url)

		_resource_system.load_dynamic_resource(config, _on_pck_loaded, _on_pck_load_failed)
	else:
		# Desktop platform: load directly from res://, no HTTP needed
		var pck_path: String = "res://dist/" + pck_file
		var success: bool = ProjectSettings.load_resource_pack(pck_path)
		if success:
			_on_pck_loaded({"loaded": true, "pck_path": pck_path})
		else:
			_on_pck_load_failed("Failed to load PCK: %s" % pck_path)


func _on_pck_loaded(result: Variant) -> void:
	# Handle both Dictionary result (from ResourceSystem) and direct call
	var loaded: bool = false
	var pck_path: String = ""

	if result is Dictionary:
		var result_dict: Dictionary = result
		loaded = result_dict.get("loaded", false)
		pck_path = result_dict.get("pck_path", "")
	else:
		loaded = true

	if not loaded:
		log_error("[FontSystem] PCK load returned false")
		_pck_status = PckStatus.FAILED
		return

	_pck_status = PckStatus.LOADED
	log_info("[FontSystem] PCK loaded: %s" % pck_path)

	# PCK loaded, now load all fonts
	_load_all_fonts()


func _on_pck_load_failed(error: Variant) -> void:
	var error_str: String = str(error)
	log_error("[FontSystem] PCK load failed: %s" % error_str)
	_pck_status = PckStatus.FAILED

	# Emit load failed event for all fonts
	for font_key: String in _fonts:
		var info: FontInfo = _fonts[font_key]
		info.status = FontStatus.FAILED
		info.error_message = "PCK load failed: %s" % error_str
		_emit_load_failed(font_key, info.error_message)


# ========================================
# Font Loading (from PCK)
# ========================================

func _load_all_fonts() -> void:
	for font_key: String in _fonts:
		_load_font_from_pck(font_key)


func _load_font_from_pck(font_key: String) -> void:
	if not _fonts.has(font_key):
		log_error("[FontSystem] Font '%s' not in manifest" % font_key)
		return

	var info: FontInfo = _fonts[font_key]
	info.status = FontStatus.LOADING

	# Load from PCK internal path
	var font_path: String = info.path  # res://fonts/xxx.otf

	# For PCK-loaded files, we need to read file data directly
	# because ResourceLoader.load() may not work for dynamically loaded PCK
	var file: FileAccess = FileAccess.open(font_path, FileAccess.READ)
	if file == null:
		log_error("[FontSystem] Font not found in PCK: %s" % font_path)
		info.status = FontStatus.FAILED
		info.error_message = "Font not found in PCK"
		_emit_load_failed(font_key, info.error_message)
		return

	var data: PackedByteArray = file.get_buffer(file.get_length())
	file.close()

	if data.is_empty():
		log_error("[FontSystem] Font file is empty: %s" % font_path)
		info.status = FontStatus.FAILED
		info.error_message = "Font file is empty"
		_emit_load_failed(font_key, info.error_message)
		return

	# Create FontFile and set data
	var font_file: FontFile = FontFile.new()
	font_file.data = data

	# Configure font rendering options
	font_file.antialiasing = TextServer.FONT_ANTIALIASING_LCD
	font_file.hinting = TextServer.HINTING_LIGHT
	font_file.subpixel_positioning = TextServer.SUBPIXEL_POSITIONING_AUTO

	# Store font
	info.font_file = font_file
	info.status = FontStatus.LOADED

	log_info("[FontSystem] Font '%s' loaded from PCK (%d bytes)" % [font_key, data.size()])

	# Apply default font to theme if this is the default
	if font_key == _default_font_key:
		_apply_default_font(font_file)

	# Emit loaded event
	_emit_font_loaded(font_key, font_file)


# ========================================
# Theme Management
# ========================================

func _apply_default_font(font: FontFile) -> void:
	var theme: Theme = ThemeDB.get_project_theme()
	if theme == null:
		log_warn("[FontSystem] No project theme configured")
		return

	theme.default_font = font
	log_info("[FontSystem] Applied font to project theme")


# ========================================
# Event Emission
# ========================================

func _emit_font_loaded(font_key: String, font: FontFile) -> void:
	if _event_system == null:
		return

	var event: FontLoadedEvent = FontLoadedEvent.new()
	event.font_key = font_key
	event.font = font
	_event_system.trigger(event)


func _emit_load_failed(font_key: String, error_message: String) -> void:
	if _event_system == null:
		return

	var event: FontLoadFailedEvent = FontLoadFailedEvent.new()
	event.font_key = font_key
	event.error_message = error_message
	_event_system.trigger(event)


# ========================================
# Helpers
# ========================================

## Get the base URL for web platform (directory containing index.html)
func _get_web_base_url() -> String:
	if not OS.has_feature("web"):
		return ""

	# Use JavaScript to get the current page URL and extract the base path
	var js_code: String = """
		(function() {
			var url = window.location.href;
			var lastSlash = url.lastIndexOf('/');
			return url.substring(0, lastSlash + 1);
		})()
	"""
	var result: Variant = JavaScriptBridge.eval(js_code)
	if result == null:
		log_error("[FontSystem] Failed to get web base URL via JavaScriptBridge")
		return ""
	return str(result)
