extends SceneTree

## Add UIDs to .tscn files (and optionally .gd files)
## Usage: 
##   godot --headless --script tools/add_scene_uids.gd
##   godot --headless --script tools/add_scene_uids.gd -- --scripts
## 
## By default, only processes .tscn files for better performance (<1s).
## Use --scripts flag to also process .gd files (slower, usually unnecessary).
## 
## Note: .gd.uid files are automatically generated by Godot during build/export.
## Only use --scripts if you need UIDs before building.

var PROCESS_SCRIPTS: bool = false

func _init() -> void:
	# Parse command line arguments
	# When using: godot --headless --script file.gd -- args
	# Arguments after -- are available in OS.get_cmdline_user_args()
	var args: PackedStringArray = OS.get_cmdline_user_args()
	for arg: String in args:
		if arg == "--scripts":
			PROCESS_SCRIPTS = true
			break
	
	print("=== Adding UIDs to resource files ===")
	if PROCESS_SCRIPTS:
		print("Mode: Processing .tscn and .gd files")
	else:
		print("Mode: Processing .tscn files only")
	
	var files_to_process: Array[String] = []
	_find_resource_files("res://", files_to_process)
	
	print("Found %d resource files" % files_to_process.size())
	
	for file_path: String in files_to_process:
		if file_path.ends_with(".tscn"):
			_add_uid_to_scene(file_path)
		elif PROCESS_SCRIPTS and file_path.ends_with(".gd"):
			_add_uid_to_script(file_path)
	
	print("\n✓ UID processing complete")
	quit()

func _find_resource_files(path: String, result: Array[String]) -> void:
	var dir: DirAccess = DirAccess.open(path)
	if not dir:
		return
	
	dir.list_dir_begin()
	var file_name: String = dir.get_next()
	
	while file_name != "":
		if file_name.begins_with("."):
			file_name = dir.get_next()
			continue
		
		var full_path: String = path + "/" + file_name if path != "res://" else path + file_name
		
		if dir.current_is_dir():
			_find_resource_files(full_path, result)
		elif file_name.ends_with(".tscn"):
			result.append(full_path)
		elif PROCESS_SCRIPTS and file_name.ends_with(".gd"):
			result.append(full_path)
		
		file_name = dir.get_next()
	
	dir.list_dir_end()

func _add_uid_to_scene(scene_path: String) -> void:
	# Check if scene already has UID
	var file: FileAccess = FileAccess.open(scene_path, FileAccess.READ)
	if not file:
		print("  ✗ Failed to open: %s" % scene_path)
		return
	
	var first_line: String = file.get_line()
	file.close()
	
	# Check if UID already exists
	if first_line.contains("uid="):
		print("  - %s (already has UID)" % scene_path)
		return
	
	# Generate new UID (using Godot's official method)
	# create_id_for_path generates deterministic UIDs based on:
	# - Project name
	# - File path  
	# - File content (MD5)
	# This matches what Godot Editor does
	var new_uid: int = ResourceUID.create_id_for_path(scene_path)
	ResourceUID.add_id(new_uid, scene_path)
	var uid_string: String = ResourceUID.id_to_text(new_uid)
	
	# Read entire file
	file = FileAccess.open(scene_path, FileAccess.READ)
	var content: String = file.get_as_text()
	file.close()
	
	# Modify first line to add UID
	var lines: PackedStringArray = content.split("\n")
	if lines.size() > 0 and lines[0].begins_with("[gd_scene"):
		# Parse the existing line
		var first: String = lines[0]
		if first.contains("format="):
			# Insert uid before the closing bracket
			first = first.replace("]", " uid=\"%s\"]" % uid_string)
			lines[0] = first
			
			# Write back
			file = FileAccess.open(scene_path, FileAccess.WRITE)
			file.store_string("\n".join(lines))
			file.close()
			
			print("  ✓ %s -> %s" % [scene_path, uid_string])
		else:
			print("  ✗ %s (unexpected format)" % scene_path)
	else:
		print("  ✗ %s (not a valid scene file)" % scene_path)

func _add_uid_to_script(script_path: String) -> void:
	# Check if .uid file already exists
	var uid_file_path: String = script_path + ".uid"
	if FileAccess.file_exists(uid_file_path):
		print("  - %s (already has .uid file)" % script_path)
		return
	
	# Generate new UID for the script
	var new_uid: int = ResourceUID.create_id_for_path(script_path)
	ResourceUID.add_id(new_uid, script_path)
	var uid_string: String = ResourceUID.id_to_text(new_uid)
	
	# Write .uid file
	var file: FileAccess = FileAccess.open(uid_file_path, FileAccess.WRITE)
	if file:
		file.store_line(uid_string)
		file.close()
		print("  ✓ %s -> %s" % [script_path, uid_string])
	else:
		print("  ✗ Failed to create .uid file for %s" % script_path)
