#!/usr/bin/env python3
"""
Generate ResourceTypes enum from @resource annotations in GDScript files.

This script scans all .gd files in scripts/systems/ for @resource annotations
and generates a resource_types.gd file with the enum definitions.

Usage:
    python tools/generate_resource_types.py

Annotation format in GDScript files:
    ## @resource IMAGE:RESOURCE_TYPE_IMAGE:0
    ## @resource AUDIO:RESOURCE_TYPE_AUDIO:1

    The third part (value) is REQUIRED to ensure stable enum values.
    If no value is specified, the script will fail with an error.

Output:
    generated/resource_types.gd
"""

import os
import re
import sys


def scan_resource_annotations(scripts_dir: str) -> dict:
    """Scan all .gd files for @resource annotations.
    
    Args:
        scripts_dir: Path to scripts/systems directory
    
    Returns:
        Dictionary mapping enum name to (config_name, value)
        e.g. {"IMAGE": ("RESOURCE_TYPE_IMAGE", 0), "AUDIO": ("RESOURCE_TYPE_AUDIO", 1)}
    """
    resource_types = {}
    errors = []
    
    if not os.path.exists(scripts_dir):
        print(f"Warning: Directory not found: {scripts_dir}")
        return resource_types
    
    for root, dirs, files in os.walk(scripts_dir):
        for file in files:
            if file.endswith(".gd"):
                path = os.path.join(root, file)
                try:
                    with open(path, 'r', encoding='utf-8') as f:
                        content = f.read()
                        # Match ## @resource TYPE:CONFIG_NAME:VALUE (value is required)
                        matches_with_value = re.findall(r'##\s*@resource\s+(\w+):(\w+):(\d+)', content)
                        # Also check for old format without value (to report error)
                        matches_without_value = re.findall(r'##\s*@resource\s+(\w+):(\w+)(?!:\d)', content)
                        
                        for type_name, config_name, value in matches_with_value:
                            if type_name in resource_types:
                                errors.append(f"Duplicate resource type '{type_name}' in {path}")
                            else:
                                int_value = int(value)
                                # Check for duplicate values
                                for existing_name, (_, existing_value) in resource_types.items():
                                    if existing_value == int_value:
                                        errors.append(f"Duplicate enum value {int_value} for '{type_name}' and '{existing_name}'")
                                resource_types[type_name] = (config_name, int_value)
                        
                        for type_name, config_name in matches_without_value:
                            # Skip if already found with value
                            if type_name not in resource_types:
                                errors.append(f"Missing enum value for @resource {type_name}:{config_name} in {path}")
                                errors.append(f"  Fix: ## @resource {type_name}:{config_name}:<VALUE>")
                except Exception as e:
                    errors.append(f"Error reading {path}: {e}")
    
    if errors:
        print("Errors found:")
        for error in errors:
            print(f"  {error}")
        return None
    
    return resource_types


def generate_resource_types_file(resource_types: dict, output_path: str) -> None:
    """Generate the resource_types.gd file.
    
    Args:
        resource_types: Dictionary mapping enum name to (config_name, value)
        output_path: Path to output .gd file
    """
    # Sort types by value for consistent ordering in the generated file
    sorted_types = sorted(resource_types.items(), key=lambda x: x[1][1])  # Sort by value
    
    # Generate enum items with explicit values
    enum_items = [f"\t{name} = {value}," for name, (_, value) in sorted_types]
    
    # Generate TYPE_NAMES mapping (config name -> Type)
    type_names_items = [f'\t"{config_name}": Type.{name}' for name, (config_name, _) in sorted_types]
    
    # Generate TYPE_TO_NAME mapping (Type -> config name) for O(1) reverse lookup
    type_to_name_items = [f'\tType.{name}: "{config_name}"' for name, (config_name, _) in sorted_types]
    
    content = f'''# Auto-generated by generate_resource_types.py
# DO NOT EDIT MANUALLY

class_name ResourceTypes extends RefCounted

## Resource type enum
## Generated from @resource annotations in system files
## Values are explicitly defined to ensure stability
enum Type {{
{chr(10).join(enum_items)}
}}

## Type names mapping (config name -> Type)
const TYPE_NAMES: Dictionary = {{
{("," + chr(10)).join(type_names_items)}
}}

## Reverse mapping (Type -> config name) for O(1) lookup
const TYPE_TO_NAME: Dictionary = {{
{("," + chr(10)).join(type_to_name_items)}
}}

## Get enum value from config name
static func from_config_name(name: String) -> int:
	return TYPE_NAMES.get(name, Type.JSON)


## Get config name from enum value
static func to_config_name(type: int) -> String:
\treturn TYPE_TO_NAME.get(type, "RESOURCE_TYPE_IMAGE")
'''
    
    # Ensure output directory exists
    output_dir = os.path.dirname(output_path)
    if output_dir and not os.path.exists(output_dir):
        os.makedirs(output_dir)
    
    with open(output_path, 'w', encoding='utf-8') as f:
        f.write(content)


def main():
    # Get project root (parent of tools/)
    script_dir = os.path.dirname(os.path.abspath(__file__))
    project_root = os.path.dirname(script_dir)
    
    scripts_dir = os.path.join(project_root, "scripts", "systems")
    output_path = os.path.join(project_root, "generated", "resource_types.gd")
    
    print(f"Scanning for @resource annotations in: {scripts_dir}")
    
    resource_types = scan_resource_annotations(scripts_dir)
    
    if resource_types is None:
        print("\nGeneration failed due to errors above.")
        print("Please fix the @resource annotations and try again.")
        return 1
    
    if not resource_types:
        print("No @resource annotations found, using defaults...")
        # Default types if no annotations found (with explicit values)
        resource_types = {
            "ATLAS": ("RESOURCE_TYPE_ATLAS", 0),
            "AUDIO": ("RESOURCE_TYPE_AUDIO", 1),
            "IMAGE": ("RESOURCE_TYPE_IMAGE", 2),
            "JSON": ("RESOURCE_TYPE_JSON", 3),
            "PCK": ("RESOURCE_TYPE_PCK", 4),
            "SCENE": ("RESOURCE_TYPE_SCENE", 5)
        }
    
    generate_resource_types_file(resource_types, output_path)
    
    print(f"Generated {len(resource_types)} resource types:")
    for name, (config_name, value) in sorted(resource_types.items(), key=lambda x: x[1][1]):
        print(f"  - {name} = {value}: {config_name}")
    print(f"Output: {output_path}")
    
    return 0


if __name__ == "__main__":
    sys.exit(main())
